### ISSUE TITLE
DOCKER安装后无法启动

### ISSUE THREAD

**Issue by WHHGR** [Mystery00/telegram-channel-publisher#1]
docker run -d \
    -e CONFIG_HOME=/app/etc \
    -v /path/to/logs:/app/logs \
    -v /path/to/config.yaml:/app/etc/config.yaml \
    mystery0/telegram-channel-publisher:latest
参照以上使用方法安装了DOCKER容器就停止，在相关路径修改了config.yaml文件，依然启动不了呢

**Comment by Mystery00** [comment]
贴一下日志呢，如果挂载出来了，可以直接看宿主机目录的日志文件 /path/to/logs/publisher.log

**Comment by WHHGR** [comment]
日志也没有报错原因，只有启动记录，但是实际上并没有启动。。。
<img width="200" alt="1" src="https://github.com/Mystery00/telegram-channel-publisher/assets/78685509/1a563bb0-4d00-49f2-b7b6-213af64cb047">
<img width="627" alt="2" src="https://github.com/Mystery00/telegram-channel-publisher/assets/78685509/815a90d1-995d-4315-bbfd-649fe963577d">
<img width="324" alt="3" src="https://github.com/Mystery00/telegram-channel-publisher/assets/78685509/d7d6b2a4-5c77-4055-9424-4e45ec2f594a">
<img width="278" alt="4" src="https://github.com/Mystery00/telegram-channel-publisher/assets/78685509/86d31817-a8d9-43d9-8809-31a0a0b212d8">
<img width="365" alt="5" src="https://github.com/Mystery00/telegram-channel-publisher/assets/78685509/b1610fd9-2449-4b4c-937e-365aa4705f7d">

**Comment by Mystery00** [comment]
配置文件去掉敏感数据之后发出来看一下，同时把调试模式打开
![image](https://github.com/Mystery00/telegram-channel-publisher/assets/19162205/0433e1b5-33c9-4507-9098-aae5c931aff1)

**Comment by WHHGR** [comment]
我试试，配置文件基本按照你的说明来弄的

bot:
  # 机器人的token
  token: "{{XXXXXXX}}"
  # 机器人的接入点信息，如果部署的服务器无法访问Telegram，可以使用代理的形式来访问
  endpoint: ""
  # 指定频道id，如果指定，那么只有对应频道的消息才会被处理，如果不指定，那么所有频道的消息都会被处理
  channel: "XXXXXXX"
  # 需要过滤的频道消息，这里可以填上对应的标签，例如：["tag1", "tag2"]，那么就会过滤任何包含 “#tag1”、“#tag2” 的消息
  filter: [ ]

log:
  home: "logs"
  file: "publisher.log"
  color: false
  local: false
  # 调试模式，出现问题的时候建议打开，会输出更多的日志信息
  debug: false

publisher:
  # 发布的类型，目前只支持log和halo，log是将内容输出到日志文件，halo是将内容发布到Halo的瞬间
  type: "halo"

halo:
  # Halo的访问域名，例如 https://blog.mystery0.vip
  host: "{{ https://XXXXX}}"
  # Halo的token 参考下图进行创建
  token: "{{XXXXXXXX}}"
  image:
    # 消息中的图片的分组信息，最好是在管理后台自己创建一个分组专门放瞬间的图片，方便管理，可为空
    group: "瞬间"
    # 消息中的图片的存储策略，参考后续内容进行获取
    policy: "{{全部}}"

**Comment by WHHGR** [comment]
![image](https://github.com/Mystery00/telegram-channel-publisher/assets/78685509/cfc70680-5f8a-4e0d-88f6-09f8d33c2845)

**Comment by Mystery00** [comment]
服务器能访问 https://api.telegram.org 吗，curl一下看看

**Comment by WHHGR** [comment]
甲骨文的机器，没问题吧

root@debian:~# wget https://api.telegram.org
--2023-11-10 12:50:23--  https://api.telegram.org/
正在解析主机 api.telegram.org (api.telegram.org)... 149.154.167.220, 2001:67c:4e8:f004::9
正在连接 api.telegram.org (api.telegram.org)|149.154.167.220|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 302 Moved Temporarily
位置：https://core.telegram.org/bots [跟随至新的 URL]
--2023-11-10 12:50:24--  https://core.telegram.org/bots
正在解析主机 core.telegram.org (core.telegram.org)... 149.154.167.99, 2001:67c:4e8:f004::9
正在连接 core.telegram.org (core.telegram.org)|149.154.167.99|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：16370 (16K) [text/html]
正在保存至: “index.html”

index.html                               100%[===============================================================================>]  15.99K  --.-KB/s  用时 0s      

2023-11-10 12:50:26 (225 MB/s) - 已保存 “index.html” [16370/16370])

root@debian:~# curl -I https://api.telegram.org
HTTP/2 302 
server: nginx/1.18.0
date: Fri, 10 Nov 2023 04:51:04 GMT
content-type: text/html
content-length: 145
location: https://core.telegram.org/bots
strict-transport-security: max-age=31536000; includeSubDomains; preload
access-control-allow-origin: *
access-control-allow-methods: GET, POST, OPTIONS
access-control-expose-headers: Content-Length,Content-Type,Date,Server,Connection

**Comment by Mystery00** [comment]
机器cpu架构是arm的吗

**Comment by WHHGR** [comment]
> 机器cpu架构是arm的吗

嗯，是的，arm的

**Comment by Mystery00** [comment]
方便换成 amd64 试试吗，看起来似乎是arm64的镜像有点什么问题

**Comment by WHHGR** [comment]
> 方便换成 amd64 试试吗，看起来似乎是arm64的镜像有点什么问题

好，我换个AMD试试

**Comment by WHHGR** [comment]
换了台AMD机器，系统debian12
出现同样的情况，无法启动，启动就停止。日志内容也一模一样

**Comment by Mystery00** [comment]
你 docker logs 一下应该就能看到错误信息了

**Comment by Mystery00** [comment]
https://github.com/Mystery00/telegram-channel-publisher/blob/main/bot/bot.go#L25

看情况，应该还是连接telegram bot api出了什么问题导致的

**Comment by WHHGR** [comment]
root@debian:~# docker logs --details a62fb3557a69
 2023-11-10 06:10:49.333 [INFO] [main] Starting server...
 2023-11-10 06:10:49.795 [PANI] Not Found
 panic: (*logrus.Entry) 0xc00047a1c0
 
 goroutine 1 [running]:
 github.com/sirupsen/logrus.(*Entry).log(0xc00047a150, 0x0, {0xc00008e440, 0x9})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x491
 github.com/sirupsen/logrus.(*Entry).Log(0xc00047a150, 0x0, {0xc00015d9d8?, 0x40df65?, 0x10?})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
 github.com/sirupsen/logrus.(*Entry).Logln(0xc00047a150, 0x0, {0xc00015da28?, 0x6?, 0xc00015da98?})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:394 +0x7f
 telegram-channel-publisher/config.(*logHook).Fire(0xc000040160, 0xc00047a070)
        /usr/local/go/src/telegram-channel-publisher/config/log.go:82 +0xea
 github.com/sirupsen/logrus.LevelHooks.Fire(0xc00015db28?, 0x15daf8?, 0x1?)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/hooks.go:28 +0x70
 github.com/sirupsen/logrus.(*Entry).fireHooks(0xc00047a070)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:280 +0x1fa
 github.com/sirupsen/logrus.(*Entry).log(0xc00047a000, 0x0, {0xc00008e420, 0x9})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:242 +0x399
 github.com/sirupsen/logrus.(*Entry).Log(0xc00047a000, 0x0, {0xc00015de60?, 0x0?, 0x0?})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
 github.com/sirupsen/logrus.(*Logger).Log(0xbcfb40, 0x0, {0xc00015de60, 0x1, 0x1})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/logger.go:204 +0x58
 github.com/sirupsen/logrus.(*Logger).Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/logger.go:253
 github.com/sirupsen/logrus.Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/exported.go:129
 telegram-channel-publisher/bot.InitBot()
        /usr/local/go/src/telegram-channel-publisher/bot/bot.go:25 +0x156
 main.main()
        /usr/local/go/src/telegram-channel-publisher/main.go:20 +0x93
 2023-11-10 06:11:54.419 [INFO] [main] Starting server...
 2023-11-10 06:11:54.882 [PANI] Not Found
 panic: (*logrus.Entry) 0xc0000ba4d0
 
 goroutine 1 [running]:
 github.com/sirupsen/logrus.(*Entry).log(0xc0000ba460, 0x0, {0xc00047d750, 0x9})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x491
 github.com/sirupsen/logrus.(*Entry).Log(0xc0000ba460, 0x0, {0xc00006d9d8?, 0x40df65?, 0x10?})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
 github.com/sirupsen/logrus.(*Entry).Logln(0xc0000ba460, 0x0, {0xc00006da28?, 0x6?, 0x100000000000080?})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:394 +0x7f
 telegram-channel-publisher/config.(*logHook).Fire(0xc000086158, 0xc0000ba3f0)
        /usr/local/go/src/telegram-channel-publisher/config/log.go:82 +0xea
 github.com/sirupsen/logrus.LevelHooks.Fire(0xc00006db28?, 0x6daf8?, 0x6?)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/hooks.go:28 +0x70
 github.com/sirupsen/logrus.(*Entry).fireHooks(0xc0000ba3f0)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:280 +0x1fa
 github.com/sirupsen/logrus.(*Entry).log(0xc0000f6930, 0x0, {0xc00047d730, 0x9})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:242 +0x399
 github.com/sirupsen/logrus.(*Entry).Log(0xc0000f6930, 0x0, {0xc00006de60?, 0x0?, 0x0?})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
 github.com/sirupsen/logrus.(*Logger).Log(0xbcfb40, 0x0, {0xc00006de60, 0x1, 0x1})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/logger.go:204 +0x58
 github.com/sirupsen/logrus.(*Logger).Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/logger.go:253
 github.com/sirupsen/logrus.Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/exported.go:129
 telegram-channel-publisher/bot.InitBot()
        /usr/local/go/src/telegram-channel-publisher/bot/bot.go:25 +0x156
 main.main()
        /usr/local/go/src/telegram-channel-publisher/main.go:20 +0x93
 2023-11-10 06:19:03.526 [INFO] [main] Starting server...
 2023-11-10 06:19:03.997 [PANI] Not Found
 panic: (*logrus.Entry) 0xc0004781c0
 
 goroutine 1 [running]:
 github.com/sirupsen/logrus.(*Entry).log(0xc000478150, 0x0, {0xc000012450, 0x9})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x491
 github.com/sirupsen/logrus.(*Entry).Log(0xc000478150, 0x0, {0xc00006d9d8?, 0x40df65?, 0x10?})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
 github.com/sirupsen/logrus.(*Entry).Logln(0xc000478150, 0x0, {0xc00006da28?, 0x6?, 0x100000000000080?})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:394 +0x7f
 telegram-channel-publisher/config.(*logHook).Fire(0xc000086158, 0xc000478070)
        /usr/local/go/src/telegram-channel-publisher/config/log.go:82 +0xea
 github.com/sirupsen/logrus.LevelHooks.Fire(0xc00006db28?, 0x6daf8?, 0x6?)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/hooks.go:28 +0x70
 github.com/sirupsen/logrus.(*Entry).fireHooks(0xc000478070)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:280 +0x1fa
 github.com/sirupsen/logrus.(*Entry).log(0xc000478000, 0x0, {0xc000012430, 0x9})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:242 +0x399
 github.com/sirupsen/logrus.(*Entry).Log(0xc000478000, 0x0, {0xc00006de60?, 0x0?, 0x0?})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
 github.com/sirupsen/logrus.(*Logger).Log(0xbcfb40, 0x0, {0xc00006de60, 0x1, 0x1})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/logger.go:204 +0x58
 github.com/sirupsen/logrus.(*Logger).Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/logger.go:253
 github.com/sirupsen/logrus.Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/exported.go:129
 telegram-channel-publisher/bot.InitBot()
        /usr/local/go/src/telegram-channel-publisher/bot/bot.go:25 +0x156
 main.main()
        /usr/local/go/src/telegram-channel-publisher/main.go:20 +0x93

**Comment by Mystery00** [comment]
😀 不会是bot token填错了吧

**Comment by Mystery00** [comment]
token的前后你加了{{}}吗，那个{{}}我只是用来表示它是一个需要改的东西，实际用的时候需要删掉

**Comment by WHHGR** [comment]
配置文件里所有的{{}} 括号都要删除的？

**Comment by Mystery00** [comment]
> 配置文件里所有的{{}} 括号都要删除的？

是的，迟会我会发一个新版本，同时更新一下部署文档，你可以等一下再试试

**Comment by WHHGR** [comment]
苍天。。。
我去掉了所以括号。。。

**Comment by WHHGR** [comment]
然后 。。。好了。。。ARM的也可以
![image](https://github.com/Mystery00/telegram-channel-publisher/assets/78685509/8154c666-e4ee-4a88-8b0e-f96f6b32e503)

**Comment by WHHGR** [comment]
但是加图片发布不了呢，我再研究一下

**Comment by Mystery00** [comment]
> 但是加图片发布不了呢，我再研究一下

图片不行是因为你配置里面那个存储策略填的不对，README里面我有写怎样获取正确的值

**Comment by WHHGR** [comment]
> > 但是加图片发布不了呢，我再研究一下
> 
> 图片不行是因为你配置里面那个存储策略填的不对，README里面我有写怎样获取正确的值

搞定了  非常感谢

**Comment by Mystery00** [comment]
README已经更新了，可以试一下1.0.2版本，再出现之前那个问题现在可以在日志文件中看到原因了
1.0.2版本配置文件格式有一点小小的改动

**Comment by WHHGR** [comment]
> README已经更新了，可以试一下1.0.2版本，再出现之前那个问题现在可以在日志文件中看到原因了 1.0.2版本配置文件格式有一点小小的改动

谢谢啦，已更新 期待更多好用的功能
