### ISSUE TITLE
telegram 中#开头的标签语句只会发布标签

### ISSUE THREAD

**Issue by jp0id** [Mystery00/telegram-channel-publisher#2]
例如频道中是: "#北京 今天天气不错。"
而Halo的瞬间只有: "#北京"

**Comment by Mystery00** [comment]
telegram的标签解析是根据空格分隔的，所以 “#天气 今天天气不错”中只有“#天气”是标签

J.P ***@***.***> 于 2023年11月13日周一 14:19写道：

**Comment by Mystery00** [comment]
欸，是指解析出错了吗，我试试

**Comment by Mystery00** [comment]
![image](https://github.com/Mystery00/telegram-channel-publisher/assets/19162205/896265cb-e19a-47c8-91ee-154b273b628f)

没有复现

**Comment by jp0id** [comment]
可是我刚才测试了一下，还是有问题。难道需要更新？
![image](https://github.com/Mystery00/telegram-channel-publisher/assets/35218851/3741ebfb-1c47-4971-884c-c2460b35b030)
<img width="349" alt="image" src="https://github.com/Mystery00/telegram-channel-publisher/assets/35218851/149be18b-00a3-4e75-8780-9a36dbfa84c2">

**Comment by jp0id** [comment]
更新了**docker镜像**之后，频道中的信息无法同步到`瞬间`，日志也没有出错，不知道什么原因。

**Comment by Mystery00** [comment]
![image](https://github.com/Mystery00/telegram-channel-publisher/assets/19162205/bc83cafa-3bce-4229-b7cf-539262809649)
依旧没有复现

方便把配置文件敏感信息处理一下之后，给我看一下配置吗

**Comment by jp0id** [comment]
还原了一下镜像，使用`20231101-19f6`没有问题，如果使用`latest`就不会痛不。当然，那个`标签`问题还是一样的。

**Comment by Mystery00** [comment]
> 还原了一下镜像，使用`20231101-19f6`没有问题，如果使用`latest`就不会痛不。当然，那个`标签`问题还是一样的。

1.0.0版本之前的镜像和现在的配置文件有不同的地方，建议重新按照README重新写一次配置文件（有少部分字段改动了），然后使用最新版本的镜像（尝试使用指定tag而不是latest）

**Comment by Jv0id** [comment]
`bot:
  # 机器人的token
  token: "6*********oA"
  # 机器人的接入点信息，如果部署的服务器无法访问Telegram，可以使用代理的形式来访问
  endpoint: ""
  # 指定频道id，如果指定，那么只有对应频道的消息才会被处理，如果不指定，那么所有频道的消息都会被处理
  channel: "-100****"

log:
  home: "logs"
  file: "publisher.log"
  color: false
  local: false
  # 调试模式
  debug: false

publisher:
  # 发布的类型，目前只支持log和halo，log是将内容输出到日志文件，halo是将内容发布到Halo的瞬间
  type: "halo"

halo:
  host: "https://*****.com"
  # Halo的token 参考下图进行创建
  token: "pat_eyJraWQiOiJNaUdxcm5sREF5RlphMDZCWDFoOURubmIwTy1VT2V6U05pNnRsQms**********"
  image:
    # 消息中的图片的分组信息，最好是在管理后台自己创建一个分组专门放瞬间的图片，方便管理，可为空
    group: "attachment-group-dgVTs"
    # 消息中的图片的存储策略，参考后续内容进行获取
    policy: "default-policy"`

**Comment by Jv0id** [comment]
bot:
  # 机器人的token
  token: "6*********oA"
  # 机器人的接入点信息，如果部署的服务器无法访问Telegram，可以使用代理的形式来访问
  endpoint: ""
  # 指定频道id，如果指定，那么只有对应频道的消息才会被处理，如果不指定，那么所有频道的消息都会被处理
  channel: "-100****"

log:
  home: "logs"
  file: "publisher.log"
  color: false
  local: false
  # 调试模式
  debug: false

publisher:
  # 发布的类型，目前只支持log和halo，log是将内容输出到日志文件，halo是将内容发布到Halo的瞬间
  type: "halo"

halo:
  host: "https://*****.com"
  # Halo的token 参考下图进行创建
  token: "pat_eyJraWQiOiJNaUdxcm5sREF5RlphMDZCWDFoOURubmIwTy1VT2V6U05pNnRsQms**********"
  image:
    # 消息中的图片的分组信息，最好是在管理后台自己创建一个分组专门放瞬间的图片，方便管理，可为空
    group: "attachment-group-dgVTs"
    # 消息中的图片的存储策略，参考后续内容进行获取
    policy: "default-policy"

**Comment by jp0id** [comment]
> > 还原了一下镜像，使用`20231101-19f6`没有问题，如果使用`latest`就不会痛不。当然，那个`标签`问题还是一样的。
> 
> 1.0.0版本之前的镜像和现在的配置文件有不同的地方，建议重新按照README重新写一次配置文件（有少部分字段改动了），然后使用最新版本的镜像（尝试使用指定tag而不是latest）

我再看一下readme

**Comment by jp0id** [comment]
应该没有问题了，使用了`latest`镜像，使用最新的配置文件，发布功能和**标签**问题已经解决了。感谢。
